/**
 * Created by LucyQiao on 7/6/16.
 */
//using flicker API:
// https://www.flickr.com/services/api/flickr.photos.search.html
//*********************Variable Declaration*****************************

var div = document.getElementById("outter");
//the photo selected for lightbox to show
var selectedPhoto = document.getElementById("lightBoxImage");
//the photo's title
var photoTitle = document.getElementById("title");
//number of photo to show
var n = 30;
//array of photos
var allPhotos = [];

//*********************Initalizing Photo*****************************

function initialize() {
    var xhr = new XMLHttpRequest();
    var grid = document.getElementById("gridArea");
    var searchKeyword = document.getElementById("request").value.trim();

    //if there is an element
    if(searchKeyword !== null) {
        //url generated by flicker api https://www.flickr.com/services/api/explore/flickr.photos.search
       var url = "https://api.flickr.com/services/rest/?method=flickr.photos.search&api_key=c0e2dcf2a49e24683baf7ef09710f95b&sort=relevance&safe_search=1&content_type=1&extras=url_s&per_page="
            + n +"&page=1&format=json&nojsoncallback=1&text=" +searchKeyword;

        //reset gridArea before every search
        grid.innerHTML = '';

        getPhoto(xhr,url);
    } else {
        console.log("No search keyword entered.");
    }
}


/*
 * get the photo data and either goes to print the grid
 * or generates an error
 */
function getPhoto(xhr,url) {
    //Send a Request To a Server
    xhr.open('GET', url, true);

    xhr.onload = function() {
        //Get photo data successfully
        if(xhr.status == 200) {
            var data = JSON.parse(xhr.responseText);
            printGrid(data);
        }else {
            console.log("Photo couldn't be loaded successfully.");
        }
    };

    xhr.send();
}

/*
 * prints the photos as a grid
 *
 */
function printGrid(data) {
    allPhotos = [];
    var i;
    var gridList = data.photos.photo;
    var size = gridList.length;
    var grid =document.getElementById("gridArea");

    for(i=0;i<size;i++) {
        allPhotos.push(gridList[i]);
        var thumbnail = document.createElement("img");
        var link = document.createElement("i");

        thumbnail.setAttribute("src", gridList[i].url_s);
        thumbnail.setAttribute("class", "thumbnail");

        thumbnail.setAttribute("id", i);


        link.setAttribute("href", "#");
        link.setAttribute("onclick", "open('" + gridList[i].url_s + "'," + i + ",'" + gridList[i].title.replace(/'/g, "\\'") + "')");

        link.appendChild(thumbnail);
        grid.appendChild(link);
    }
}


/**********************************LightBox**********************************
/*
 * when ueser clicks on one photo, opens lightbox mode
 *
 */
function open(url, id, title) {
    div.style.display = "block";
    //updates the selectedPhoto to a larger version
    selectedPhoto.setAttribute("src", url.replace("_s.jpg", "_c.jpg"));
    //its new id is updated
    selectedPhoto.setAttribute("data-id", id);
    photoTitle.textContent = title;

    //continues to check user's button pressing
    backAndForth(selectedPhoto.dataset.id);
}

/*
 * when the user uses next or previous buttons
 *
 */
function backAndForth(index) {
    var prev = document.getElementById("previous");
    var nxt = document.getElementById("next");

    //check whether the selectedPhoto is the first photo (1st photo cannot go to prev)
    if (index == 0) {
        nxt.style.display = "block";
        prev.style.display = "none";

        //otherwise, its NOT the first photo, therefore can go to previous photo
    } else {
        prev.style.display = "block";

        //if selectedPhoto is the last image, can't go to next
        if (index == n - 1) {
            nxt.style.display = "none";
        } else {
            nxt.style.display = "block";
        }
    }

}

/*
 * returns to grid when the user uses exit button
 */
function exit() {
    div.style.display = "none";
    //changes selectedPhoto to null basically
    selectedPhoto.setAttribute("src", "");
    selectedPhoto.setAttribute("data-id", "");
}

/*
 * goes to the previous photo in lightbox mode
 */
function previous() {
    //decrements index to signal going backward in allPhotos[]
    var updatedIndex = parseInt(selectedPhoto.dataset.id) - 1;
    var updatedUrl = getLarger(updatedIndex);

    if (updatedIndex > -1) {
        selectedPhoto.setAttribute("src", updatedUrl);
        selectedPhoto.setAttribute("data-id", updatedIndex);
        photoTitle.textContent = getTitle(updatedIndex);
    }

    //continues to check user's button pressing
    backAndForth(selectedPhoto.dataset.id);
}

function next() {
    //increments index to signal going forwared in allPhotos[]
    var updatedIndex = parseInt(selectedPhoto.dataset.id) + 1;
    var updatedUrl = getLarger(updatedIndex);

    if (updatedIndex < n - 1) {
        selectedPhoto.setAttribute("src", updatedUrl);
        selectedPhoto.setAttribute("data-id", updatedIndex);
        photoTitle.textContent = getTitle(updatedIndex);
    }

    //continues to check user's button pressing
    backAndForth(selectedPhoto.dataset.id);
}



/**
 * returns the title of the photo
 */
function getTitle(index) {
    return allPhotos[index].title;
}
/*
 * returns the URL for the smaller image
 */
function getSmaller(index) {
    return allPhotos[index].url_c.replace("_c.jpg", "_s.jpg");
}

/*
 * returns the URL for the larger image
 */
function getLarger(index) {
    return allPhotos[index].url_s.replace("_s.jpg", "_c.jpg");
}


